before:
  hooks:
    - go mod tidy
builds:
  - id: yakv
    main: .
    binary: yakv
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - 386
    ignore:
    - goos: darwin
      goarch: 386
    - goos: linux
      goarch: 386
archives:
- name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: binary